# Generated by Django 4.2 on 2024-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrica',
            name='anio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='electrica',
            name='descripcion',
            field=models.CharField(default='sin descripcion', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electrica',
            name='precio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='electrica',
            name='serial',
            field=models.IntegerField(null=True),
        ),
    ]
